CREATE TABLE shoe_inventory (
  id INT NOT NULL AUTO_INCREMENT,
  brand VARCHAR(50) NOT NULL,
  model VARCHAR(50) NOT NULL,
  colorway VARCHAR(50) NOT NULL,
  size  DECIMAL(3,1) NOT NULL,
  price DECIMAL(10, 2) NOT NULL,
  quantity INT NOT NULL,
  styleCode VARCHAR(50) NOT NULL,
  sku VARCHAR(50) NOT NULL UNIQUE,
  PRIMARY KEY (id)
);


CREATE TABLE shoe_sale (
	id INT NOT NULL AUTO_INCREMENT,
	sku VARCHAR(50) NOT NULL,
    price DECIMAL(10,2) NOT NULL,
    sale_date DATE NOT NULL,
    PRIMARY KEY (id)
);
